[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[build.environment]
  NODE_VERSION = "18"

# Custom headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect www to non-www
[[redirects]]
  from = "https://www.pageantempress.com/*"
  to = "https://pageantempress.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.pageantempress.com/*"
  to = "https://pageantempress.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://pageantempress.com/*"
  to = "https://pageantempress.com/:splat"
  status = 301
  force = true

# Pretty URLs
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/gallery.html"
  status = 200

# Blog post routing
[[redirects]]
  from = "/blog/:slug"
  to = "/blog-post.html?slug=:slug"
  status = 200

# API routes to Netlify Functions
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

[[redirects]]
  from = "/api/newsletter"
  to = "/.netlify/functions/newsletter"
  status = 200

[[redirects]]
  from = "/api/instagram"
  to = "/.netlify/functions/instagram"
  status = 200

# Sitemap routing
[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

# Social media shortcuts
[[redirects]]
  from = "/instagram"
  to = "https://www.instagram.com/pageantempress"
  status = 302

[[redirects]]
  from = "/youtube"
  to = "https://www.youtube.com/pageantempress"
  status = 302

# 404 fallback
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Functions directory
[functions]
  directory = "netlify/functions"
