[build]
  # Build command (if you have a build process)
  command = "npm run build"
  
  # Directory to publish (change if your files are in a different folder)
  publish = "."
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Edge functions (if needed)
# [[edge_functions]]
#   function = "geolocation"
#   path = "/api/*"

# Form handling
[forms]
  # Enable form handling
  spam_protection = true

# Functions (if using Netlify Functions)
[functions]
  directory = "netlify/functions"
